# Generated by Django 4.0.5 on 2022-06-15 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название ингредиента', max_length=256, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(choices=[('г', 'г'), ('кг', 'кг'), ('мл', 'мл'), ('л', 'л'), ('ст. л.', 'ст. л.'), ('ч. л.', 'ч. л.'), ('банка', 'банка'), ('батон', 'батон'), ('бутылка', 'бутылка'), ('веточка', 'веточка'), ('горсть', 'горсть'), ('долька', 'долька'), ('звездочка', 'звездочка'), ('зубчик', 'зубчик'), ('капля', 'капля'), ('кусок', 'кусок'), ('лист', 'лист'), ('пакет', 'пакет'), ('пакетик', 'пакетик'), ('пачка', 'пачка'), ('пласт', 'пласт'), ('по вкусу', 'по вкусу'), ('пучок', 'пучок'), ('стакан', 'стакан'), ('стебель', 'стебель'), ('стручок', 'стручок'), ('тушка', 'тушка'), ('упаковка', 'упаковка'), ('шт.', 'шт.'), ('щепотка', 'щепотка')], max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0, message='Убедитесь, что значение больше 0.')], verbose_name='количество')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название рецепта', max_length=200, verbose_name='Название рецепта')),
                ('image', models.ImageField(upload_to='foodgram/', verbose_name='Картинка')),
                ('text', models.TextField(help_text='Введите описание рецепта', max_length=500)),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, message='Убедитесь, что значение больше 0.')], verbose_name='Время приготовления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(choices=[('HOTPINK', '#FF69B4'), ('SALMON', '#FA8072'), ('GREEN', '#32CD32'), ('BLUE', '#87CEFA'), ('BROWN', '#F4A460')], max_length=7, unique=True, verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(unique=True, verbose_name='Краткое название')),
            ],
        ),
        migrations.CreateModel(
            name='TagRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Выберите рецепт', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
                ('tag', models.ForeignKey(help_text='Выберите теги рецепта', on_delete=django.db.models.deletion.CASCADE, to='recipes.tag', verbose_name='Тэги')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Выберите рецепты для добавления в корзину', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='recipes.recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
